### ISSUE TITLE
cgt error: plain is not valid for encryption parameters

### ISSUE THREAD

**Issue by pjattke** [momalab/e3#8] opened 2020-09-10 17:38 UTC
When trying to run the following program, I receive the error message:

```
cgt error (std): plain is not valid for encryption parameters
```

@momalab @educhielle Could you kindly provide help regarding this error. When not using any negated values, it works flawless. I am very confused as SEAL should support negative numbers.

Thanks a lot!

**Source code**

```
#include <iostream>
#include "e3int.h"
#include "../e3key.h"

using namespace std;

// #ifndef SZ
// #define SZ 8
// #endif

using SecureInt  = TypeUint<SZ>;
using SecureBool = TypeBool;
using SecureMint = TypeMint;


int main()
{
  // = INPUTS ===
  // flags
  SecureMint man = _1_Em;
  SecureMint not_man = _1_Em;

  std::cout << e3::decrypt(man*not_man) << '\n';
}

```

**cgt.cfg**

```
password = hello_world

@sizes = 8

SealBridge : bridge
{
	encryption = seal
	encoder = batch
	module = bridge.seal
	polyModulusDegree = 15 # 2^15
	plaintextModulus = 65537 # 2
}

TypeMint : ring
{
	postfix = Ea
	postneg = Em
	encryption = @SealBridge
}

Type : circuit
{
	postfix = Ep
	postneg = En
	encryption = @SealBridge
	circuitDB = seal
}
```

**Comment by pjattke** [comment] 2020-09-10 18:08
By using the `Type : circuit`, i.e., `  SecureMint man = _1_En; SecureMint not_man = _1_En;` it works but takes rather long. Also, when using `encryption = seal_ckks` it works. However, I need to use BFV with arithmetic circuits. Are negative values not supported in BFV with arithmetic (type `ring`)?

**Comment by pjattke** [comment] 2020-09-10 20:29
I am pretty sure that the error is somehow related to E3 as using the same parameters in a naive SEAL program works.

Here's the program's code:
```
#include <iostream>
#include "seal/seal.h"

using namespace seal;

int main() {
  EncryptionParameters parms(scheme_type::BFV);
  size_t poly_modulus_degree = 32768;
  parms.set_poly_modulus_degree(poly_modulus_degree);
  parms.set_coeff_modulus(CoeffModulus::BFVDefault(poly_modulus_degree));
  parms.set_plain_modulus(65537);
  auto context = SEALContext::Create(parms);

  // generate helper objects
  KeyGenerator keygen(context);
  PublicKey public_key = keygen.public_key();
  SecretKey secret_key = keygen.secret_key();
  Encryptor encryptor(context, public_key);
  Evaluator evaluator(context);
  Decryptor decryptor(context, secret_key);
  BatchEncoder encoder(context);

  // generate ciphertext for -1
  seal::Plaintext p1;
  std::vector<int64_t> data = {-1};
  encoder.encode(data, p1);
  seal::Ciphertext c1;
  encryptor.encrypt(p1, c1);

  // compute -1 * -1
  evaluator.multiply_inplace(c1, c1);

  // decrypt and decode result
  seal::Plaintext d1;
  decryptor.decrypt(c1, d1);
  std::vector<int64_t> dec;
  encoder.decode(d1, dec);

  std::cout << dec[0] << std::endl;
}
```

This prints as expected `1`.

**Comment by educhielle** [comment] 2020-09-11 11:43
The ring type works in modular arithmetic [0,t-1], where t is the plaintext modulus.
At the moment CGT doesn't define a _postneg_ parameter for the ring type, so it won't automatically convert -1 to t-1. In this case, you have to do it manually. For example: `auto minus_one = -SecureMint(_1_Ea);`

Here is how your code would look like:

**Source code**
```
#include <iostream>
#include "e3int.h"
#include "e3key.h"

using namespace std;

#ifndef SZ
#define SZ 8
#endif

using SecureInt  = TypeUint<SZ>;
using SecureBool = TypeBool;
using SecureMint = TypeMint;


int main()
{
  // = INPUTS ===
  // flags
  auto man = -SecureMint(_1_Ea);
  auto not_man = -SecureMint(_1_Ea);

  std::cout << e3::decrypt(man*not_man) << '\n';
}
```

**cgt.cfg**
```
password = hello_world

@sizes = 8

SealBridge : bridge
{
	encryption = seal
	encoder = batch
	module = bridge.seal
	polyModulusDegree = 15 # 2^15
	plaintextModulus = 65537 # 2
}

TypeMint : ring
{
	postfix = Ea
	encryption = @SealBridge
}

Type : circuit
{
	postfix = Ep
	postneg = En
	encryption = @SealBridge
	circuitDB = seal
}
```

You should see `_1_1...` as output.
With batch encoder, the constant value is assigned to all slots of the ciphertext, so when you do `SecureMint one = _1_Ea`, you are setting all slots of the ciphertext _one_ to 1. If you want only the first slot to be one and the rest to be zero, then you should do `SecureMint one = _1_0_Ea`. You can also do any combination you want, e.g. `_2_3_5_7_11_0_Ea`.

I hope it helped. I will answer to this thread once we add postneg to the ring type.

**Comment by pjattke** [comment] 2020-09-11 19:30
Dear @educhielle,
Thank you so much for your help and the sample code. Using the technique described, I could successfully implement my program. 

Many thanks again. Wish you a nice weekend!

**Comment by mazonka** [comment] 2020-09-17 06:53
I cannot reproduce the error. Can you please provide with minimal 'cfg' and 'cpp'  files?

**Comment by pjattke** [comment] 2020-09-17 06:59
@mazonka This is already resolved. I defined negative values as described by @educhielle (e.g., `SecureMint i = -SecureMint(_1_Ea);`). If the program given in my [first post](https://github.com/momalab/e3/issues/8#issue-698283316) works for you without any issues, please let me know so I can give you more details to reproduce it.

**Comment by mazonka** [comment] 2020-09-17 08:06
This is a workaround. With your original code I am getting the result 0 (for SEAL=0, which is also incorrect, but it is another problem). But I do not get cgt error. I am concerned about that error.

**Closed as completed** 2022-11-29 01:24 UTC
